### ISSUE TITLE
PyPI package has a wrong repository link

### ISSUE THREAD

**Issue by Korne127** [dmgbuild/dmgbuild#108]
The [PyPI project site](https://pypi.org/project/dmgbuild/) of this project as well as the one of the other organisation projects [ds-store](https://pypi.org/project/ds-store/) and [mac-alias](https://pypi.org/project/mac-alias/) all have outdated links. If you click source, you get GitHub 404 errors. It would be good if these could be updated to the current organisation repository links.

**Comment by freakboy3742** [comment]
Thanks for the report. The links are definitely *old* - but at least for me, they're still resolving (the dmgbuild links both resolve to the dmgbuild/dmgbuild project on Github. However, they should definitely be updated to reflect this directly.

**Comment by Korne127** [comment]
Oh, it depends where you click

If you click on Homepage on the left bar:
![image](https://github.com/dmgbuild/dmgbuild/assets/33464213/696654c4-1706-4c48-abde-db7d3d04d88a)

it leads to http://alastairs-place.net/projects/ds_store and redirects to this repository (https://github.com/dmgbuild/ds_store) correctly.

However, if you click on "Source" (which is what I did), it leads to https://github.com/al45stair/ds_store leading to a 404 error:
![image](https://github.com/dmgbuild/dmgbuild/assets/33464213/26452551-9c77-422d-95d7-c94a07e552cc)

The licence and CI buttons on the top
![Bildschirmfoto 2024-05-16 um 23 43 31](https://github.com/dmgbuild/dmgbuild/assets/33464213/e6fcfde9-ff72-4c46-971b-708988751f8a)

directly lead to the correct links in this repository.

**Comment by Korne127** [comment]
@freakboy3742 I'm sorry, but sadly this issue is still not resolved. :/
If you go to https://pypi.org/project/dmgbuild/, all the links are still as I described them. Maybe you need to release a new version or push these changes to `pypi` somehow for them to take effect?

**Comment by freakboy3742** [comment]
Yes - I would need to publish a new release for these changes to take effect. However, given that this is a relatively cosmetic change, that in itself isn't a trigger for cutting a new release.

**Comment by freakboy3742** [comment]
v1.6.2 has now been released, so the URLs are now updated.

**Comment by Korne127** [comment]
Yay, that's really great to hear!
