### ISSUE TITLE
Expose detach_retries via command line or settings file

### ISSUE THREAD

**Issue by tfmorris** [dmgbuild/dmgbuild#128]
Unless I'm missing something, it doesn't appear that the detach retry count which was added in #22 can be set either from the command line or the settings file. Would it be possible to expose this setting?

Our builds using Github Actions are failing approximately once every 40 builds with the default setting of 5 retries, so we'd like to try increasing it to see if that helps.

**Comment by freakboy3742** [comment]
I can't see any reason it couldn't be added as an option; it looks like a fairly straight shot to add the argument to `dmg_build/__main__.py`. I'd be happy to take a look at a PR.
