### ISSUE TITLE
license adding broken on Big Sur

### ISSUE THREAD

**Issue by fizzyade** [dmgbuild/dmgbuild#29]
hditool under macOS 11 (Big Sur)  does not support the flatten/unflatten commands which are used by this when adding a license to the DMG.

**Comment by EddieAguirre** [comment]
Could something like this work? https://github.com/create-dmg/create-dmg/commit/f75cc032d77672adab60cebd49db000a8ff7446a

**Comment by al45tair** [comment]
@EddieAguirre Yes, it looks like that would work. If anyone fancies doing a PR, I'm open to merging a fix. (I won't be able to work on dmgbuild myself for much longer, and I don't know whether I'll find the time before then to fix this myself.)

**Comment by freakboy3742** [comment]
Fixed in #43.
