### ISSUE TITLE
How to run dmbguild on macOS 13.2

### ISSUE THREAD

**Issue by jaroslavas** [dmgbuild/dmgbuild#45]
After updating to macOS 13.2 dmgbuildstopped working. It crashes with error:
```
dmgbuild
-bash: ~/Library/Python/2.7/bin/dmgbuild: No such file or directory
```

Any ideas how to fix that?

**Comment by dehesselle** [comment]
You need to reinstall it with e.g. `pip3 install dmgbuild` (assuming you have Xcode installed, which provides Python 3). The latest update to macOS removed the old Python 2.7 runtime.
You can also remove that folder `~/Library/Python/2.7` as it no longer serves any purpose.

**Comment by freakboy3742** [comment]
Closing as resolved.
