### ISSUE TITLE
Missing badge.py dependency Quartz

### ISSUE THREAD

**Issue by simtind** [dmgbuild/dmgbuild#50]
Since https://github.com/dmgbuild/dmgbuild/commit/fe60f4b290403ccdf17f78502f9033e70dbff52a removed Quartz as a dependency from the setup scripts, it's no longer possible to import badge.py unless Quartz happens to be installed through some other dependency.

**Comment by freakboy3742** [comment]
This requirement is defined in the documentation for `badge_icon`; however, it could definitely be accommodated as an installation extra. I'll make that change to the docs and configuration.
