### ISSUE TITLE
Documentation Correction - badge_icon

### ISSUE THREAD

**Issue by scottfurry** [dmgbuild/dmgbuild#54]
Readthedocs page covering settings contains a description that seems inconsistent with package pypi footprint. From the description for [`badge_icon` setting](https://dmgbuild.readthedocs.io/en/latest/settings.html#badge_icon):

>The use of badge icons requires that dmg_build be installed with the badge_icons extra; i.e., you need to install dmg_build using:

> `pip install "dmg_build[badge_icons]"`

I'm assuming that package _use to be named_ `dmg_build` or an underscore was inserted by error (my fat fingers do similar).

**Comment by freakboy3742** [comment]
Oops - yup, that's a typo. A fix is incoming.

**Comment by scottfurry** [comment]
grep, [ack](https://beyondgrep.com/) or similar can be your friend when scouring the tree.
_use the source, Luke_

Thanks for prompt reply.

**Comment by adrianinsaval** [comment]
@freakboy3742 today I get this:
`WARNING: dmgbuild 1.6.5 does not provide the extra 'badge_icons'`
So I gu

**Comment by freakboy3742** [comment]
@adrianinsaval Thanks for the report; I've opened #214 to track the problem, and provide the immediate workaround.
