### ISSUE TITLE
No language combobox in Eula dialog

### ISSUE THREAD

**Issue by Enoxyzz** [dmgbuild/dmgbuild#56]
We have upgraded to latest version of DmgBuild, version 1.6.
Installed Python 3.8 for it, working on MacOS BigSur.
Now we don't get a language-pulldown anymore on the license agreement dialog.
It selects the default language (english) for buttons and instruction text.
But the license-rtf file shown is the one that is mentioned as the last one in the licenses list in our settings file.
Any ideas?
Can't find any changes in the parameters in the documentation.
Do I need an additional parameter to show that combobox?

**Comment by freakboy3742** [comment]
DMGBuild 1.6 updated the tool that is used to compile license content (See #43); it's possible that transition has introduced a bug. Are you able to share a minimal reproduction case?

**Comment by Enoxyzz** [comment]
I can show you a part of our Python settings file:
<pre>
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os.path
import plistlib

bgimage = defines.get('bgimg', 'builtin-arrow')

def icon_from_app(app_path):
    plist_path = os.path.join(app_path, 'Contents', 'Info.plist')
    # old plist = biplist.readPlist(plist_path)
    with open(plist_path, "rb") as f:
        plist = plistlib.load(f)	
    icon_name = plist['CFBundleIconFile']
    icon_root,icon_ext = os.path.splitext(icon_name)
    if not icon_ext:
        icon_ext = '.icns'
    icon_name = icon_root + icon_ext
    return os.path.join(app_path, 'Contents', 'Resources', icon_name)

[....]

licensedir = defines.get('euladir', '')

license = {
    'default-language': 'en_US',
    'licenses': {
        'de_DE': licensedir + 'de/license_de.rtf',
        'es_ES': licensedir + 'es/license_es.rtf',
        'en_US': licensedir + 'en/license_en.rtf',
        'fr_FR': licensedir + 'fr/license_fr.rtf'
    }
}
</pre>
So in this case, the French RTF-file is shown, with English buttons, and no pulldown.

On MacOS 10.14 it's working fine with the older dmgbuild tool.
Meanwhile I was able to add the license to the DMG via another tool (dmg-license).
So now we only use dmgbuild to create the DMG, which works fine.

**Comment by freakboy3742** [comment]
Thanks for those details. This is one of those cases where it's difficult for me to test locally - I don't have a lot of experience with switching between languages, so it's difficult for me to evaluate when things are working correctly. Any assistance you (or anyone else) can provide in diagnosing and fixing this would be most appreciated.
