### ISSUE TITLE
Extra files in dmg

### ISSUE THREAD

**Issue by samirg1** [dmgbuild/dmgbuild#62]
Hi there,
I love this tool and it has been working great for me. I build with a settings file that is pretty much the exact same as the one you provided. One thing I noticed recently is if I am viewing hidden files in Finder (cmd+shift+.) and I open my dmg it has two extra files `.background.tiff` and `.VolumeIcon.icns` and since these sort higher than my app the window does not display properly.
I have tried to use the `hide` parameter in the settings file but these still show up.

My current solution is to include them in the `icon_locations` so that I can at least place them out of view (unless you scroll). I was just wondering if there is any way to completely hide them.

**Comment by freakboy3742** [comment]
To the best of my knowledge, this isn't something that can be worked around. The files need to exist in the DMG to be usable; they rely on the names being hidden to make them invisible to most users. If you're showing hidden files... then you're going to see them - there's no secret hole you can put them in where they won't be visible files on the filesystem.

Closing on the basis that it's not technically possible (AFAIK). If anyone has information to the contrary, I'd be happy to integrate that change.
