### ISSUE TITLE
Unable to run under Linux distributions

### ISSUE THREAD

**Issue by acidhorse1972** [dmgbuild/dmgbuild#63]
This app only runs in the MacOS terminal command line and not on OpenSUSE and probably not on any other Linux distros.

```
Traceback (most recent call last):
  File "/usr/bin/dmgbuild", line 5, in <module>
    from dmgbuild.__main__ import main
  File "/usr/lib/python3.11/site-packages/dmgbuild/__init__.py", line 1, in <module>
    from .core import build_dmg
  File "/usr/lib/python3.11/site-packages/dmgbuild/core.py", line 32, in <module>
    MACOS_VERSION = tuple(int(v) for v in platform.mac_ver()[0].split("."))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dmgbuild/core.py", line 32, in <genexpr>
    MACOS_VERSION = tuple(int(v) for v in platform.mac_ver()[0].split("."))
                          ^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

**Comment by freakboy3742** [comment]
Given that dmgbuild depends on macOS-specific tooling like `/usr/bin/hdiutil`, I don't think it's reasonable to expect that it will *ever* run on Linux. 

If someone wants to contribute patches to add Linux (or Windows) support, I'll happily consider them; but until then, this isn't really a bug - it's "off label usage".

**Comment by acidhorse1972** [comment]
Well it's not realy a bug report but a documentation issue. 
The dmgbuild readme doesn't state that it must be ran on MacOS and that lead to the confusion.
The mac_alias readme does state it and that clued me in.

**Comment by umlaeute** [comment]
i agree with @acidhorse1972

stumbling upon this project, i was under the impression that i would be able to run this on Linux, only to find out that I get errors when running `dmgbuild -h`.

please add a `Requirements` section to your README that mentions `macOS`
